# Generated by Django 4.2.16 on 2024-10-23 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0008_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='name',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='image',
            field=models.ImageField(upload_to='donor_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blood_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodbankapp.bloodgroup'),
        ),
        migrations.AlterField(
            model_name='requestblood',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
