# Generated by Django 4.2.16 on 2024-10-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0009_alter_bloodgroup_name_alter_bloodrequest_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blood_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bloodbankapp.bloodgroup'),
        ),
    ]
